version: '3.8'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'postgres_db'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'PastiBisa888!'
      POSTGRES_DB: 'db_sekolah'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://postgres:PastiBisa888!@145.223.18.208:5432/db_sekolah'
    depends_on:
      - postgres

volumes:
  postgres_data:

